import type {
  CeramicImage,
  CeramicMaterial,
  ClayBodyProfile,
  ConversationPreview,
  FiringEnvironmentRecord,
  FiringLogPoint,
  FiringRecord,
  FiringSegment,
  GlazeApplication,
  GlazeApplicationLayer,
  GlazeProfile,
  GlazeRecipeVersion,
  KilnProfile,
  Post,
  Profile,
} from "./domain";

export const profiles: Profile[] = [
  {
    id: "profile-mara",
    displayName: "Mara Chen",
    username: "marachen",
    avatarColor: "#8f4f3a",
    biography: "Cone 10 reduction, porcelain test tiles, and quiet bowls.",
    profileType: "artist",
    identityLabel: "Ceramic artist",
    email: "mara@example.com",
    authProvider: "email",
    emailVerified: true,
    locationLabel: "Pacific Northwest",
    website: "https://example.com/mara",
    specialties: ["reduction glazes", "porcelain", "kiln logs"],
    preferredTemperatureUnit: "c",
    preferredWeightUnit: "g",
    preferredWindSpeedUnit: "kph",
    profileVisibility: "public",
    subscriptionTier: "business",
    businessProfile: {
      businessName: "Mara Chen Ceramics",
      description: "Small-batch porcelain, reduction glaze research, and kiln-opening workshops.",
      websiteUrl: "https://example.com/mara",
      instagram: "@marachenstudio",
      etsy: "marachenpots",
      googleMapsUrl: "https://maps.google.com/?q=Mara+Chen+Ceramics",
      businessHours: "By appointment, Friday-Sunday",
      contactEmail: "studio@example.com",
      contactPhone: "(555) 014-0420",
      publicStudioAddress: "Pacific Northwest studio, address shared for workshops",
      servicesOffered: ["production pottery", "workshops", "commissions", "kiln rental"],
      portfolioHeroImageColor: "#9bb4bd",
    },
    onboardingComplete: true,
  },
  {
    id: "profile-jules",
    displayName: "Jules Navarro",
    username: "julespots",
    avatarColor: "#315d67",
    biography: "Soda firing and clay-body tests for community classes.",
    profileType: "educator",
    identityLabel: "Teaching artist",
    email: "jules@example.com",
    authProvider: "google",
    authProviderId: "google-julespots",
    emailVerified: true,
    locationLabel: "Northern California",
    specialties: ["soda", "stoneware", "teaching"],
    preferredTemperatureUnit: "f",
    preferredWeightUnit: "lb",
    preferredWindSpeedUnit: "mph",
    profileVisibility: "public",
    subscriptionTier: "free",
    onboardingComplete: true,
  },
];

export const ceramicMaterials: CeramicMaterial[] = [
  { id: "mat-custer", name: "Custer Feldspar", category: "flux" },
  { id: "mat-silica", name: "Silica 325 mesh", category: "silica" },
  { id: "mat-epk", name: "EPK Kaolin", category: "clay" },
  { id: "mat-whiting", name: "Whiting", category: "flux" },
  { id: "mat-red-iron", name: "Red Iron Oxide", category: "colorant" },
  { id: "mat-rutile", name: "Rutile", category: "colorant" },
];

export const kilns: KilnProfile[] = [
  {
    id: "kiln-skutt-1227",
    ownerId: "profile-mara",
    name: "North Room 1227",
    manufacturer: "Skutt",
    model: "KM-1227",
    kilnType: "electric",
    fuelType: "electric",
    controllerType: "digital Bartlett",
    usableVolumeLiters: 262,
    maxTemperatureC: 1315,
    recommendedConeRange: "06-10",
    defaultLocation: "indoors",
    powerKw: 11.5,
    active: true,
    visibility: "private",
    notes: "Elements replaced after Firing 041; top ring runs slightly cool.",
  },
  {
    id: "kiln-bailey-gas",
    ownerId: "profile-mara",
    name: "Bailey Downdraft",
    manufacturer: "Bailey",
    model: "Custom 24 cu ft",
    kilnType: "gas",
    fuelType: "natural gas",
    controllerType: "manual pyrometer",
    usableVolumeLiters: 680,
    maxTemperatureC: 1320,
    recommendedConeRange: "6-11",
    defaultLocation: "semi_enclosed",
    active: true,
    visibility: "followers",
    notes: "Reduction is strongest near lower back shelf.",
  },
  {
    id: "kiln-soda-yard",
    ownerId: "profile-jules",
    name: "Yard Soda Kiln",
    manufacturer: "Studio-built",
    model: "Crossdraft",
    kilnType: "soda",
    fuelType: "propane",
    controllerType: "manual",
    usableVolumeLiters: 430,
    maxTemperatureC: 1305,
    recommendedConeRange: "6-10",
    defaultLocation: "outdoors_partially_covered",
    active: true,
    visibility: "public",
    notes: "Wind affects early heatwork; record gusts carefully.",
  },
];

export const clayBodies: ClayBodyProfile[] = [
  {
    id: "clay-bali-speckled",
    ownerId: "profile-mara",
    name: "Bali Speckled Stoneware",
    manufacturer: "Laguna",
    supplier: "Local clay supplier",
    bodyType: "stoneware",
    rawColor: "warm gray",
    firedColor: "buff with iron speckle",
    texture: "medium grog",
    grogPercentage: 8,
    absorptionPercentage: 1.9,
    shrinkagePercentage: 12.4,
    coneRange: "5-10",
    atmosphereSuitability: ["oxidation", "reduction", "soda"],
    recipeVisibility: "private",
    profileVisibility: "public",
    notes: "Stable for mugs and bowls; occasional bloating above cone 11.",
    imageColor: "#b9855f",
  },
  {
    id: "clay-arctic-porcelain",
    ownerId: "profile-mara",
    name: "Arctic Porcelain",
    manufacturer: "Plainsman",
    supplier: "Studio reclaim blend",
    bodyType: "porcelain",
    rawColor: "cool white",
    firedColor: "translucent white",
    texture: "smooth",
    absorptionPercentage: 0.6,
    shrinkagePercentage: 14.2,
    coneRange: "6-10",
    atmosphereSuitability: ["oxidation", "reduction"],
    recipeVisibility: "private",
    profileVisibility: "followers",
    notes: "Needs slow dry and careful preheat for larger rims.",
    imageColor: "#ede8dd",
  },
];

export const glazes: GlazeProfile[] = [
  {
    id: "glaze-tenmoku",
    ownerId: "profile-mara",
    name: "Quiet Tenmoku",
    creatorAttribution: "Adapted from studio archive",
    source: "Mara Chen test series",
    glazeType: "tenmoku",
    surface: "glossy breaking brown",
    colorFamily: ["black", "brown", "amber"],
    opacity: "opaque",
    firingRange: "1260-1300C",
    coneRange: "9-10",
    atmosphereCompatibility: ["reduction", "heavy_reduction"],
    recipeVisibility: "private",
    profileVisibility: "public",
    description: "A steady iron glaze with amber breaks on trimmed edges.",
    applicationNotes: "Best at medium thickness over iron-bearing stoneware.",
    heroImageColor: "#221713",
    currentRecipeVersionId: "recipe-tenmoku-v3",
  },
  {
    id: "glaze-nuka-blue",
    ownerId: "profile-mara",
    name: "Nuka Blue Ash",
    creatorAttribution: "Public studio recipe, credited",
    source: "Community glaze exchange",
    glazeType: "ash",
    surface: "satin pooling blue",
    colorFamily: ["blue", "cream", "gray"],
    opacity: "translucent",
    firingRange: "1220-1280C",
    coneRange: "6-10",
    atmosphereCompatibility: ["oxidation", "reduction", "soda"],
    recipeVisibility: "public",
    profileVisibility: "public",
    description: "A nuka-style ash glaze that pools pale blue in texture.",
    applicationNotes: "Avoid heavy application near foot rings.",
    heroImageColor: "#9bb4bd",
    currentRecipeVersionId: "recipe-nuka-v2",
  },
  {
    id: "glaze-celadon",
    ownerId: "profile-jules",
    name: "Jun Field Celadon",
    creatorAttribution: "Jules Navarro",
    source: "Soda series 2026",
    glazeType: "celadon",
    surface: "glossy translucent",
    colorFamily: ["green", "blue"],
    opacity: "translucent",
    firingRange: "1245-1290C",
    coneRange: "8-10",
    atmosphereCompatibility: ["reduction", "soda"],
    recipeVisibility: "followers",
    profileVisibility: "public",
    description: "Soft green celadon that warms under soda vapor.",
    applicationNotes: "Two second dip on porcelain or pale stoneware.",
    heroImageColor: "#9db9a0",
    currentRecipeVersionId: "recipe-celadon-v1",
  },
];

export const glazeRecipeVersions: GlazeRecipeVersion[] = [
  {
    id: "recipe-tenmoku-v2",
    glazeId: "glaze-tenmoku",
    versionNumber: 2,
    effectiveDate: "2026-02-14",
    batchSizeGrams: 1000,
    totalDryWeightGrams: 1000,
    ingredients: [
      { materialId: "mat-custer", materialName: "Custer Feldspar", percentage: 48, weightGrams: 480, role: "base" },
      { materialId: "mat-silica", materialName: "Silica 325 mesh", percentage: 24, weightGrams: 240, role: "base" },
      { materialId: "mat-epk", materialName: "EPK Kaolin", percentage: 18, weightGrams: 180, role: "base" },
      { materialId: "mat-whiting", materialName: "Whiting", percentage: 10, weightGrams: 100, role: "base" },
      { materialId: "mat-red-iron", materialName: "Red Iron Oxide", percentage: 8, weightGrams: 80, role: "colorant" },
    ],
    sourceAttribution: "Studio archive, adapted",
    changeSummary: "Lowered silica slightly after crawling on porcelain.",
    privateNotes: "Keep private until cone 10 series is finished.",
    visibility: "private",
  },
  {
    id: "recipe-tenmoku-v3",
    glazeId: "glaze-tenmoku",
    versionNumber: 3,
    effectiveDate: "2026-05-22",
    batchSizeGrams: 1000,
    totalDryWeightGrams: 1000,
    ingredients: [
      { materialId: "mat-custer", materialName: "Custer Feldspar", percentage: 47, weightGrams: 470, role: "base" },
      { materialId: "mat-silica", materialName: "Silica 325 mesh", percentage: 23, weightGrams: 230, role: "base" },
      { materialId: "mat-epk", materialName: "EPK Kaolin", percentage: 20, weightGrams: 200, role: "base" },
      { materialId: "mat-whiting", materialName: "Whiting", percentage: 10, weightGrams: 100, role: "base" },
      { materialId: "mat-red-iron", materialName: "Red Iron Oxide", percentage: 8.5, weightGrams: 85, role: "colorant" },
    ],
    sourceAttribution: "Studio archive, adapted",
    changeSummary: "Raised clay content for better suspension and fewer crawled rims.",
    privateNotes: "Best result on Bali Speckled after 20 minute soak.",
    visibility: "private",
  },
  {
    id: "recipe-nuka-v2",
    glazeId: "glaze-nuka-blue",
    versionNumber: 2,
    effectiveDate: "2026-03-04",
    batchSizeGrams: 1000,
    totalDryWeightGrams: 1000,
    waterAmountGrams: 920,
    ingredients: [
      { materialId: "mat-custer", materialName: "Custer Feldspar", percentage: 38, weightGrams: 380, role: "base" },
      { materialId: "mat-silica", materialName: "Silica 325 mesh", percentage: 22, weightGrams: 220, role: "base" },
      { materialId: "mat-epk", materialName: "EPK Kaolin", percentage: 18, weightGrams: 180, role: "base" },
      { materialId: "mat-whiting", materialName: "Whiting", percentage: 22, weightGrams: 220, role: "base" },
      { materialId: "mat-rutile", materialName: "Rutile", percentage: 4, weightGrams: 40, role: "colorant" },
    ],
    sourceAttribution: "Community exchange, original author credited",
    changeSummary: "Added rutile for blue pooling over texture.",
    visibility: "public",
  },
];

export const firings: FiringRecord[] = [
  {
    id: "firing-042",
    ownerId: "profile-mara",
    title: "Cone 10 reduction bowl tests",
    readableNumber: "Firing 042",
    kilnId: "kiln-bailey-gas",
    kilnNameSnapshot: "Bailey Downdraft",
    kilnSpecSnapshot: "24 cu ft gas downdraft, manual damper, semi-enclosed shed",
    firingType: "gas",
    status: "completed",
    visibility: "followers",
    plannedStartAt: "2026-07-10T15:00:00.000Z",
    actualStartAt: "2026-07-10T15:18:00.000Z",
    actualEndAt: "2026-07-11T05:44:00.000Z",
    timezone: "America/Los_Angeles",
    leadFirer: "Mara Chen",
    targetTemperatureC: 1290,
    targetCone: "10",
    witnessConeResult: "Cone 10 soft, 11 starting",
    atmosphere: "reduction",
    loadFullnessPercentage: 82,
    totalHeatingMinutes: 866,
    totalCoolingMinutes: 1030,
    successRating: 88,
    notes: "Body reduction started at 900C. Top shelf cooler than expected.",
  },
  {
    id: "firing-041",
    ownerId: "profile-mara",
    title: "Electric cone 6 glaze fit series",
    readableNumber: "Firing 041",
    kilnId: "kiln-skutt-1227",
    kilnNameSnapshot: "North Room 1227",
    kilnSpecSnapshot: "Skutt KM-1227, elements before replacement",
    firingType: "electric",
    status: "completed",
    visibility: "private",
    plannedStartAt: "2026-06-21T16:00:00.000Z",
    actualStartAt: "2026-06-21T16:06:00.000Z",
    actualEndAt: "2026-06-22T03:22:00.000Z",
    timezone: "America/Los_Angeles",
    leadFirer: "Mara Chen",
    targetTemperatureC: 1222,
    targetCone: "6",
    witnessConeResult: "Cone 6 down, 7 touching",
    atmosphere: "oxidation",
    loadFullnessPercentage: 58,
    totalHeatingMinutes: 676,
    totalCoolingMinutes: 840,
    successRating: 73,
    notes: "Useful baseline before element replacement; preserve kiln snapshot.",
  },
  {
    id: "firing-017",
    ownerId: "profile-jules",
    title: "Windy soda test with student tiles",
    readableNumber: "Firing 017",
    kilnId: "kiln-soda-yard",
    kilnNameSnapshot: "Yard Soda Kiln",
    kilnSpecSnapshot: "Outdoor crossdraft soda kiln, propane",
    firingType: "soda",
    status: "completed",
    visibility: "public",
    plannedStartAt: "2026-07-02T14:00:00.000Z",
    actualStartAt: "2026-07-02T14:02:00.000Z",
    actualEndAt: "2026-07-03T06:15:00.000Z",
    timezone: "America/Los_Angeles",
    leadFirer: "Jules Navarro",
    targetTemperatureC: 1280,
    targetCone: "10",
    witnessConeResult: "Cone 10 down near firebox, 9 soft at door",
    atmosphere: "soda",
    loadFullnessPercentage: 76,
    totalHeatingMinutes: 973,
    totalCoolingMinutes: 1210,
    successRating: 81,
    notes: "Wind gusts during early climb; soda response strongest on right wall.",
  },
];

export const firingSegments: FiringSegment[] = [
  { id: "segment-042-1", firingId: "firing-042", segmentType: "candling", startHour: 0, endHour: 2, startTemperatureC: 24, targetTemperatureC: 110, atmosphere: "neutral", notes: "Slow climb for thicker bowls." },
  { id: "segment-042-2", firingId: "firing-042", segmentType: "body_reduction", startHour: 6.5, endHour: 8.2, startTemperatureC: 900, targetTemperatureC: 1010, atmosphere: "reduction" },
  { id: "segment-042-3", firingId: "firing-042", segmentType: "soak", startHour: 13.9, endHour: 14.4, startTemperatureC: 1284, targetTemperatureC: 1290, atmosphere: "reduction", notes: "Twenty eight minute finish soak." },
  { id: "segment-041-1", firingId: "firing-041", segmentType: "ramp", startHour: 0, endHour: 9.6, startTemperatureC: 22, targetTemperatureC: 1222, atmosphere: "oxidation" },
];

export const firingLogPoints: FiringLogPoint[] = [
  { id: "log-042-000", firingId: "firing-042", timestamp: "2026-07-10T15:18:00.000Z", elapsedMinutes: 0, targetTemperatureC: 24, actualTemperatureC: 24, atmosphere: "neutral", manual: true },
  { id: "log-042-060", firingId: "firing-042", timestamp: "2026-07-10T16:18:00.000Z", elapsedMinutes: 60, targetTemperatureC: 80, actualTemperatureC: 76, atmosphere: "neutral", manual: true },
  { id: "log-042-120", firingId: "firing-042", timestamp: "2026-07-10T17:18:00.000Z", elapsedMinutes: 120, targetTemperatureC: 110, actualTemperatureC: 116, atmosphere: "neutral", notes: "Steam gone from spyhole.", manual: true },
  { id: "log-042-390", firingId: "firing-042", timestamp: "2026-07-10T21:48:00.000Z", elapsedMinutes: 390, targetTemperatureC: 900, actualTemperatureC: 898, atmosphere: "reduction", gasPressureKpa: 2.8, damperPosition: "2.5 cm", burnerSetting: "medium", notes: "Body reduction started.", manual: true },
  { id: "log-042-690", firingId: "firing-042", timestamp: "2026-07-11T02:48:00.000Z", elapsedMinutes: 690, targetTemperatureC: 1215, actualTemperatureC: 1208, atmosphere: "reduction", gasPressureKpa: 3.2, damperPosition: "3 cm", manual: true },
  { id: "log-042-866", firingId: "firing-042", timestamp: "2026-07-11T05:44:00.000Z", elapsedMinutes: 866, targetTemperatureC: 1290, actualTemperatureC: 1292, atmosphere: "reduction", notes: "Cone 10 soft.", manual: true },
];

export const firingEnvironmentRecords: FiringEnvironmentRecord[] = [
  {
    id: "environment-042",
    firingId: "firing-042",
    kilnLocation: "semi_enclosed",
    outsideStartTemperatureC: 19,
    outsideLowC: 13,
    outsideHighC: 24,
    humidityStartPercentage: 64,
    humidityLowPercentage: 48,
    humidityHighPercentage: 72,
    windSpeedKph: 14,
    windDirection: "W",
    windGustKph: 24,
    rainConditions: "dry",
    ventilationNotes: "Shed vents open, fan on low.",
    weatherNotes: "Cooler than the previous cone 10 firing.",
  },
  {
    id: "environment-041",
    firingId: "firing-041",
    kilnLocation: "indoors",
    indoorAmbientTemperatureC: 22,
    humidityStartPercentage: 58,
    ventilationNotes: "North room exhaust fan on.",
  },
];

export const glazeApplications: GlazeApplication[] = [
  {
    id: "application-tenmoku-bowl",
    firingId: "firing-042",
    glazeId: "glaze-tenmoku",
    glazeRecipeVersionId: "recipe-tenmoku-v3",
    clayBodyId: "clay-bali-speckled",
    ceramicPieceId: "piece-bowl-12",
    method: "dipping",
    thickness: "medium",
    coats: 2,
    specificGravity: 1.46,
    bisqueTemperatureC: 999,
    kilnPosition: "lower back, near bag wall",
    shelfLevel: "2",
    orientation: "rim toward firebox",
    resultRating: 92,
    resultStatus: "successful",
    defects: [],
    notes: "Amber breaks on trimmed foot and rim; no crawling.",
  },
  {
    id: "application-nuka-over-tenmoku",
    firingId: "firing-042",
    glazeId: "glaze-nuka-blue",
    glazeRecipeVersionId: "recipe-nuka-v2",
    clayBodyId: "clay-bali-speckled",
    ceramicPieceId: "piece-cup-08",
    method: "layering",
    thickness: "variable",
    coats: 3,
    specificGravity: 1.41,
    bisqueTemperatureC: 999,
    kilnPosition: "middle left",
    shelfLevel: "3",
    orientation: "handle inward",
    resultRating: 84,
    resultStatus: "promising",
    defects: ["running"],
    notes: "Beautiful blue rivulets, but ran 3 mm near handle overlap.",
  },
];

export const glazeApplicationLayers: GlazeApplicationLayer[] = [
  { id: "layer-tenmoku-base", applicationId: "application-nuka-over-tenmoku", glazeId: "glaze-tenmoku", glazeRecipeVersionId: "recipe-tenmoku-v3", layerOrder: 1, location: "base", coats: 1 },
  { id: "layer-nuka-top", applicationId: "application-nuka-over-tenmoku", glazeId: "glaze-nuka-blue", glazeRecipeVersionId: "recipe-nuka-v2", layerOrder: 2, location: "top", coats: 2 },
];

export const images: CeramicImage[] = [
  {
    id: "image-tenmoku-bowl",
    ownerId: "profile-mara",
    storagePath: "firing-042/tenmoku-bowl-card.jpg",
    altText: "Dark tenmoku bowl with amber breaks on a speckled stoneware foot.",
    caption: "Quiet Tenmoku v3 on Bali Speckled, lower back shelf.",
    focalPoint: { x: 0.48, y: 0.42 },
    visibility: "followers",
    firingIds: ["firing-042"],
    glazeIds: ["glaze-tenmoku"],
    clayBodyIds: ["clay-bali-speckled"],
    pieceIds: ["piece-bowl-12"],
    glazeApplicationIds: ["application-tenmoku-bowl"],
  },
  {
    id: "image-nuka-cup",
    ownerId: "profile-mara",
    storagePath: "firing-042/nuka-over-tenmoku-cup.jpg",
    altText: "Cup with blue ash glaze running over a dark iron base glaze.",
    caption: "Nuka Blue over Tenmoku overlap, note controlled run near handle.",
    focalPoint: { x: 0.53, y: 0.37 },
    visibility: "public",
    firingIds: ["firing-042"],
    glazeIds: ["glaze-nuka-blue", "glaze-tenmoku"],
    clayBodyIds: ["clay-bali-speckled"],
    pieceIds: ["piece-cup-08"],
    glazeApplicationIds: ["application-nuka-over-tenmoku"],
  },
];

export const posts: Post[] = [
  {
    id: "post-firing-042",
    authorId: "profile-mara",
    authorName: "Mara Chen",
    authorUsername: "marachen",
    body: "Cone 10 reduction finished cleaner after raising clay content in Quiet Tenmoku v3. The Bali Speckled bowls were the most consistent pieces in the load.",
    createdAt: "2026-07-11T18:20:00.000Z",
    visibility: "followers",
    linkedFiringId: "firing-042",
    imageIds: ["image-tenmoku-bowl", "image-nuka-cup"],
    hashtags: ["kilnopening", "reductionfiring", "glazechemistry"],
    structuredTagLabels: ["Firing 042", "Quiet Tenmoku v3", "Bali Speckled Stoneware"],
    likes: 42,
    comments: 9,
    replies: 4,
    saves: 12,
    uniqueInteractors: 37,
    viewerLiked: true,
    locationLabel: "Pacific Northwest",
  },
  {
    id: "post-soda-017",
    authorId: "profile-jules",
    authorName: "Jules Navarro",
    authorUsername: "julespots",
    body: "Wind gusts widened the heatwork from firebox to door. The celadon stayed useful, but the student tiles near the right wall picked up the best vapor blush.",
    createdAt: "2026-07-03T17:12:00.000Z",
    visibility: "public",
    linkedFiringId: "firing-017",
    linkedGlazeId: "glaze-celadon",
    imageIds: [],
    hashtags: ["sodafiring", "teachingstudio"],
    structuredTagLabels: ["Firing 017", "Jun Field Celadon"],
    likes: 87,
    comments: 18,
    replies: 11,
    saves: 25,
    uniqueInteractors: 74,
    viewerLiked: false,
    locationLabel: "Northern California",
  },
];

export const conversations: ConversationPreview[] = [
  {
    id: "conversation-jules",
    participantName: "Jules Navarro",
    participantUsername: "julespots",
    unreadCount: 2,
    lastMessage: "Can you send the curve from the top thermocouple before the next soda load?",
    updatedAt: "2026-07-12T15:36:00.000Z",
    linkedRecordLabel: "Firing 017",
  },
  {
    id: "conversation-rin",
    participantName: "Rin Studio",
    participantUsername: "rinstudio",
    unreadCount: 0,
    lastMessage: "The porcelain tiles are tagged now. Recipe stays private.",
    updatedAt: "2026-07-10T09:18:00.000Z",
    linkedRecordLabel: "Arctic Porcelain",
  },
];

export const kilnbookSeed = {
  profiles,
  ceramicMaterials,
  kilns,
  clayBodies,
  glazes,
  glazeRecipeVersions,
  firings,
  firingSegments,
  firingLogPoints,
  firingEnvironmentRecords,
  glazeApplications,
  glazeApplicationLayers,
  images,
  posts,
  conversations,
} as const;
